# Generated by Django 3.0 on 2022-07-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('desc', models.TextField()),
                ('price', models.CharField(max_length=10)),
                ('ratting', models.CharField(max_length=10)),
            ],
        ),
    ]
