# Generated by Django 3.0 on 2022-07-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro',
            name='image',
            field=models.ImageField(default='none', upload_to='pro_imgs'),
            preserve_default=False,
        ),
    ]
