# Generated by Django 3.0 on 2022-07-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_pro_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorAcc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=10)),
                ('password', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='pro',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
