# Generated by Django 3.0 on 2022-07-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20220712_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro',
            name='vendor_id',
            field=models.IntegerField(default=''),
        ),
    ]
