# Generated by Django 3.0 on 2022-07-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_pro_vendor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro',
            name='vendor_id',
            field=models.CharField(default='', max_length=10),
        ),
    ]
