# Generated by Django 3.0 on 2022-07-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20220712_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro',
            name='vendor_id',
            field=models.IntegerField(default=0),
        ),
    ]
