# Generated by Django 3.0 on 2022-07-12 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20220712_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pro',
            old_name='vendor_id',
            new_name='vendorid',
        ),
    ]
