# Generated by Django 3.0 on 2022-07-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_remove_pro_vendorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro',
            name='v_id',
            field=models.IntegerField(default=0),
        ),
    ]
