# Generated by Django 3.0 on 2022-07-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_pro_v_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro',
            name='v_id',
            field=models.CharField(default='', max_length=10),
        ),
    ]
